export function exportTenant({ platform, tenantId, ideas = [], commandConfig = {} }) {
  const collections = ['tenants','workspaces','providers','surfaces','taskCapsules','sessionCapsules','candidateMemories','handoffs','trafficSessions','trafficCheckpoints','resources','resourceClaims','sources','sourceItems','canonicalRecords','canonicalRecordRevisions','canonicalStates','canonicalChangeSets','canonicalChangeOperations','canonicalCheckpoints','candidateIntelligence','initializationRuns','initializationSourceRuns','extensionInstallations','extensionGrants','extensionEventSubscriptions','extensionEventOutbox','auditEvents','canonicalAccessEvents','recoverySessions','failureEvents','improvementCandidates'];
  const data = Object.fromEntries(collections.map(collection => [collection,platform.store.list(collection,item => item.tenant_id === tenantId)]));
  data.principals = platform.store.list('principals', item => item.tenant_id === tenantId).map(({principal_id,tenant_id,kind,display_name,state,role_ids,revision,created_at,updated_at}) => ({principal_id,tenant_id,kind,display_name,state,role_ids,revision,created_at,updated_at}));
  const installed = new Set(data.extensionInstallations.map(item => item.extension_id));
  data.extensions = platform.store.list('extensions',item => installed.has(item.extension_id));
  data.ideas = ideas.filter(item => item.tenant_id === tenantId);
  const files = data.sourceItems.filter(item => item.privacy_state !== 'excluded' && item.storage_state === 'stored').map(item => ({source_id:item.source_id,source_item_id:item.source_item_id,name:item.display_name,size_bytes:item.size_bytes,download_path:`/v1/sources/${encodeURIComponent(item.source_id)}/items/${encodeURIComponent(item.source_item_id)}/content`}));
  return { format:'sovereign.tenant-export',format_version:1,exported_at:new Date().toISOString(),tenant_id:tenantId,command:commandConfig,data,files,notes:['Source binaries are downloaded separately through authenticated file paths.','Service credentials, authentication bindings and token hashes are excluded.','Working Continuity and historical or proposed intelligence retain their original lifecycle states.'] };
}
