import test from 'node:test';
import assert from 'node:assert/strict';
import {createSovereignPlatform} from '../src/platform/sovereign-platform.mjs';
import {previewLegacy,applyLegacy,rollbackLegacy} from '../src/portability/legacy-import.mjs';
const commit='a'.repeat(40);
function fixture(){const platform=createSovereignPlatform();const tenant=platform.command.createTenant({slug:'legacy-import',displayName:'Legacy'});const owner=platform.command.createPrincipal({tenantId:tenant.tenant_id,displayName:'Owner'});return {platform,tenantId:tenant.tenant_id,principalId:owner.principal_id,repository:'example/legacy',commit,files:[{path:'records/fact.json',content:{id:'fact.old',statement:'Historical belief',created_at:'2020-01-01T00:00:00Z'}},{path:'work/task.json',content:{id:'task.old',kind:'task_capsule',title:'Legacy work',objective:'Preserve',status:'blocked',created_at:'2021-01-01T00:00:00Z'}}]};}
test('Legacy dry run is read-only and selective apply preserves timestamps without canonizing',()=>{const args=fixture();const before=args.platform.store.exportState();const plan=previewLegacy(args);assert.deepEqual(args.platform.store.exportState(),before);const result=applyLegacy({...args,planHash:plan.plan_hash,selectedIds:plan.inventory.map(i=>i.entry_id)});assert.equal(result.canonical_writes,0);assert.equal(args.platform.store.list('canonicalRecords').length,0);assert.equal(args.platform.store.list('candidateIntelligence')[0].created_at,'2020-01-01T00:00:00.000Z');assert.equal(args.platform.store.list('taskCapsules')[0].state,'blocked');assert.equal(result.sourceChunkReplacements.length,2);rollbackLegacy({...args,receiptId:result.receipt_id});assert.equal(args.platform.store.list('taskCapsules')[0].state,'cancelled');assert.equal(args.platform.store.list('candidateIntelligence')[0].state,'rejected');assert.equal(args.platform.store.list('sources').length,2);});
test('Changed preview and changed imported state require reconciliation',()=>{const args=fixture();const plan=previewLegacy(args);assert.throws(()=>applyLegacy({...args,planHash:'wrong',selectedIds:[plan.inventory[1].entry_id]}),{code:'legacy_plan_changed'});const result=applyLegacy({...args,planHash:plan.plan_hash,selectedIds:[plan.inventory[1].entry_id]});const task=args.platform.store.list('taskCapsules')[0];args.platform.continuity.updateTaskCapsule({tenantId:args.tenantId,taskCapsuleId:task.task_capsule_id,nextAction:'New work'});assert.throws(()=>rollbackLegacy({...args,receiptId:result.receipt_id}),{code:'legacy_rollback_requires_review'});});

test('Legacy checkpoint history is bound to preview and preserved without invented traffic',()=>{const args=fixture();args.files[1].checkpoints=[{summary:'Paused for review',created_at:'2021-02-01T00:00:00Z',next_action:'Review legacy evidence'}];const plan=previewLegacy(args);const changed=structuredClone(args.files);changed[1].checkpoints[0].summary='Altered';assert.throws(()=>applyLegacy({...args,files:changed,planHash:plan.plan_hash,selectedIds:[plan.inventory[1].entry_id]}),{code:'legacy_plan_changed'});applyLegacy({...args,planHash:plan.plan_hash,selectedIds:[plan.inventory[1].entry_id]});const task=args.platform.store.list('taskCapsules')[0];assert.equal(task.next_action,'Review legacy evidence');assert.deepEqual(task.intelligence_references[0].legacy_checkpoints,args.files[1].checkpoints);assert.equal(args.platform.store.list('trafficSessions').length,0);});

test('Rice legacy types and checkpoint field names retain their meaning',()=>{const args=fixture();args.files[0].content.kind='architecture';args.files[1].checkpoints=[{summary:'Legacy progress',recorded_at:'2021-02-01T00:00:00Z',next_actions:['Review','Resume'],blocked_by:['External dependency']}];const plan=previewLegacy(args);assert.equal(plan.inventory[0].record_type,'architecture');applyLegacy({...args,planHash:plan.plan_hash,selectedIds:plan.inventory.map(item=>item.entry_id)});assert.equal(args.platform.store.list('candidateIntelligence')[0].record_type,'architecture');const task=args.platform.store.list('taskCapsules')[0];assert.equal(task.next_action,'Review\nResume');assert.deepEqual(task.blockers,['External dependency']);assert.equal(task.intelligence_references[0].legacy_checkpoints[0].recorded_at,'2021-02-01T00:00:00Z');});
